const dotenv = require("dotenv")
const path = require("path")
dotenv.config()
process.env.VIEW_PATH=path.resolve(__dirname,process.env.VIEW_PATH)
process.env.PUBLIC_PATH=path.resolve(__dirname,process.env.PUBLIC_PATH)
process.env.SSL_KEY_PATH=path.resolve(__dirname,process.env.SSL_KEY_PATH)
process.env.SSL_CERT_PATH=path.resolve(__dirname,process.env.SSL_CERT_PATH)
